<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Machinery - HTML Template | Projects Detail </title>
<!-- Stylesheets -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">


<!--Favicon-->
<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
<link rel="icon" href="images/favicon.png" type="image/x-icon">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script src="js/respond.js"></script><![endif]-->
</head>

<body>
<div class="page-wrapper">
 	
    <!-- Preloader -->
    <div class="preloader"></div>
 	
    <header class="main-header style-two">
       
        <!--Header-Upper-->
    
    <?php
    include('header.php')
    ?>

    <!--Project Single Section-->
    <section class="project-single-section">

        <div class="auto-container">
    <h2 style="color: black; padding: 10px;">C-Type Power Press</h2>
            
            <div class="inner-container">
                <!--Upper Box-->

                <div class="upper-box">
                    <div class="single-item-carousel owl-carousel owl-theme">
                        <div class="slide">
                            <div class="image">
                                <img style="height:780px; width: 1100px;" src="http://localhost/mmtrajkot/img/product/big/c-type.jpg" alt="" />
                            </div>
                        </div>
                        <!-- <div class="slide">
                            <div class="image">
                                <img src="images/resource/image-5.jpg" alt="" />
                            </div>
                        </div>
                        <div class="slide">
                            <div class="image">
                                <img src="images/resource/image-5.jpg" alt="" />
                            </div>
                        </div> -->
                    </div>
                </div>

                <!-- <h2 class="title">London Wind Energy Plant</h2> -->
                <div class="row clearfix">
                    <!--Content Box-->
                    <div style="width:100%;" class="content-column col-lg-9 col-md-8 col-sm-12 col-xs-12">
                        <div class="inner-column">
                            <div class="text">
                                <h5>FRAME:</h5>
                                <p>The frame is made of steel construction and their heavy cross section and rigiddesign assure minimum deflection and accurate alignment cast iron legs will be supplied up to 30 ton press.</p>
                                <h5>CRANK SHAFT:</h5>
                                 <p>Crank shaft materials are made of special alloy steel to withstand the effective loadsitted in busher with high accuracy.</p>                                
                                <h5>GEARS & CLUTCH:</h5>
                                <p>The gears are made of cast steel or fabricated and it teeth are generated by hobbing the clutch is provided of pin/rolling key type also it is rigid and well supported for the mass production clutch can gives continuous stroke.</p>
                                <h5>FLYWHEEL:</h5>
                                <p>The flywheel is made of high grade cast iron and is balanced for strong and releasing adequate energy for the pressing operations.</p>
                                <h5>LUBRICATION:</h5>
                                <p>An accurate lubrication system has been proved for lubrications the sliding surface and moving parts.</p>
                                <h5>TABLE & RAM:</h5>
                                <p>Table and ram are made of high grade heavy duty cast iron & properly seasoned. They are perfactly aligned to bach other to obtain high accuracy & precision press operation</p>
                                <!-- <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatems accusantium doloremqu laudantiums ut, totams our aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae duis autems vell eums iriure dolors in hendrerit saepe eveniet  in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at seds eros sed et accumsan et iusto odio dignissim. Temporibus autem quibusdam et aut officiis debitis autrerum necesy itatibus saepe evenit uts et ut voluptates repudiandae sint et molestiae non recusandae.</p>
                                <p>Architecto beatae duis autems vell eums iriure dolors in hendrerit saepe eveniet  in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at seds eros sed et accumsan et iusto odio works dignissim et autre officiis debitis autrerum sed necessitatibus saepe evenit.</p> -->
                            </div>
                            <!-- <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-dribbble"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-skype"></span></a></li>
                            </ul> -->
                        </div>
                    </div>

                    <!--Info Column-->
                    <!-- <div class="info-column col-lg-3 col-md-4 col-sm-12 col-xs-12">
                        <div class="inner-column">
                            <ul>
                                <li><span>Category : </span>Power and Energy</li>
                                <li><span>Client : </span>Energy Producers Ltd</li>
                                <li><span>Date : </span>18th Aug, 2017</li>
                                <li><span>Link : </span><a href="#">www.steelthemes.com</a></li>
                                <li><span>Rating </span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star-half-empty"></span>
                                </li>
                            </ul>
                        </div>
                    </div> -->
                </div>
                
                <!-- <div class="load-more-option">
                    <ul class="clearfix">
                        <li class="prev pull-left"><a href="#"><span class="fa fa-angle-left"></span> Prev</a></li>
                        <li class="load-more"><a href="#"><span class="fa fa-th"></span></a></li>
                        <li class="next pull-right"><a href="#">Next <span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div> -->
                <div  class="container mt-4">
                    <table style="margin-right: 500px;" class="table table-bordered table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>DESCRIPTION</th>
                                <th>3 TONS</th>
                                <th>5 TONS</th>
                                <th>10 TONS</th>
                                <th>10 TONS</th>
                                <th>20 TONS</th>
                                <th>20 TONS</th>
                                <th>30 TONS</th>
                                <th>30 TONS</th>
                                <th>50 TONS</th>
                                <th>50 TONS</th>
                                <th>75 TONS</th>
                                <th>100 TONS</th>
                                <th>150 TONS</th>
                                <th>200 TONS</th>
                                <th>250 TONS</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="alignLeft">Crank shaft diameter</td>
                                <td>38</td>
                                <td>51</td>
                                <td>60</td>
                                <td>60</td>
                                <td>76</td>
                                <td>76</td>
                                <td>83</td>
                                <td>83</td>
                                <td>105</td>
                                <td>105</td>
                                <td>121</td>
                                <td>134</td>
                                <td>152</td>
                                <td>158</td>
                                <td class="lastColumn">165</td>
                            </tr>
                            <tr class="even">
                                <td class="alignLeft">Stroke adjustment</td>
                                <td>2-25</td>
                                <td>6-25</td>
                                <td>6-25</td>
                                <td>6-51</td>
                                <td>13-51</td>
                                <td>13-76</td>
                                <td>13-63</td>
                                <td>13-76</td>
                                <td>13-76</td>
                                <td>13-102</td>
                                <td>115</td>
                                <td>127</td>
                                <td>152</td>
                                <td>158</td>
                                <td class="lastColumn">165</td>
                            </tr>
                            <tr>
                                <td class="alignLeft">Hole in ram</td>
                                <td>19</td>
                                <td>25</td>
                                <td>25.4</td>
                                <td>25.4</td>
                                <td>32</td>
                                <td>32</td>
                                <td>38</td>
                                <td>38</td>
                                <td>38</td>
                                <td>38</td>
                                <td>45</td>
                                <td>51</td>
                                <td>57</td>
                                <td>63</td>
                                <td class="lastColumn">63</td>
                            </tr>
                            <tr class="even">
                                <td class="alignLeft">Hole in bed</td>
                                <td>51</td>
                                <td>63</td>
                                <td>76</td>
                                <td>76</td>
                                <td>83</td>
                                <td>83</td>
                                <td>89</td>
                                <td>89</td>
                                <td>127</td>
                                <td>127</td>
                                <td>127</td>
                                <td>178</td>
                                <td>191</td>
                                <td>216</td>
                                <td class="lastColumn">229</td>
                            </tr>
                            <tr>
                                <td class="alignLeft">Length & width of bed</td>
                                <td>203*152</td>
                                <td>305*178</td>
                                <td>381*255</td>
                                <td>381*255</td>
                                <td>508*305</td>
                                <td>508*305</td>
                                <td>558*358</td>
                                <td>558*358</td>
                                <td>750*520</td>
                                <td>750*520</td>
                                <td>863*596</td>
                                <td>914*635</td>
                                <td>965*685</td>
                                <td>1016*736</td>
                                <td class="lastColumn">1067*778</td>
                            </tr>
                            <tr class="even">
                                <td class="alignLeft">Dist. bed to ram</td>
                                <td>127</td>
                                <td>153</td>
                                <td>205</td>
                                <td>205</td>
                                <td>280</td>
                                <td>280</td>
                                <td>292</td>
                                <td>292</td>
                                <td>406</td>
                                <td>406</td>
                                <td>483</td>
                                <td>483</td>
                                <td>495</td>
                                <td>519</td>
                                <td class="lastColumn">544</td>
                            </tr>
                            <tr>
                                <td class="alignLeft">Flywheel diameter</td>
                                <td>330</td>
                                <td>405</td>
                                <td>435</td>
                                <td>435</td>
                                <td>550</td>
                                <td>550</td>
                                <td>660</td>
                                <td>660</td>
                                <td>810</td>
                                <td>810</td>
                                <td>910</td>
                                <td>1016</td>
                                <td>1118</td>
                                <td>1150</td>
                                <td class="lastColumn">1320</td>
                            </tr>
                            <tr class="even">
                                <td class="alignLeft">Stroke per minute</td>
                                <td>85</td>
                                <td>85</td>
                                <td>75</td>
                                <td>75</td>
                                <td>60</td>
                                <td>60</td>
                                <td>60</td>
                                <td>60</td>
                                <td>55</td>
                                <td>55</td>
                                <td>50</td>
                                <td>45</td>
                                <td>40</td>
                                <td>30</td>
                                <td class="lastColumn">30</td>
                            </tr>
                            <tr>
                                <td class="alignLeft">H.P. Required</td>
                                <td>0.5</td>
                                <td>0.5</td>
                                <td>1</td>
                                <td>1</td>
                                <td>2</td>
                                <td>2</td>
                                <td>3</td>
                                <td>3</td>
                                <td>5</td>
                                <td>5</td>
                                <td>7.5</td>
                                <td>10</td>
                                <td>15</td>
                                <td>20</td>
                                <td class="lastColumn">25</td>
                            </tr>
                            <tr class="even">
                                <td class="alignLeft">Weight approx.</td>
                                <td>150</td>
                                <td>275</td>
                                <td>500</td>
                                <td>500</td>
                                <td>1000</td>
                                <td>1000</td>
                                <td>1350</td>
                                <td>1350</td>
                                <td>2750</td>
                                <td>2750</td>
                                <td>4200</td>
                                <td>5500</td>
                                <td>6600</td>
                                <td>9000</td>
                                <td class="lastColumn">11500</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <div class="auto-container">
            <p style="margin: 10px;">All dimensions are in MM.</p>
            <p style="margin: 10px;">As day to day improvements are contempated for better performance of the machine, we reserve the rights to alter the specifications without prior notice.</p>
            <p style="margin: 10px;">All the power presses combine durability with dependability. Years of experience in machinery has enabled us to offer the higest quality machine for accuracy with precision and heavy duty performance.</p>
            <p style="margin: 10px;">Acclaimed by actual users, the machines are gaining the evergrowing popularity in the field and no wonder therfore that machines are deing recommanded everywhere.
            </p>  
        </div>
    </section>
         


    <?php
   include('footer.php')
    ?>
    <!-- End Main Footer -->


</div>    
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-arrow-up"></span></div>
<script src="js/jquery.js"></script> 
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/jquery.fancybox.js"></script>
<script src="js/slick.min.js"></script>
<script src="js/mixitup.js"></script>
<script src="js/owl.js"></script>
<script src="js/appear.js"></script>
<script src="js/wow.js"></script>
<script src="js/script.js"></script>
</body>
</html>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
