<?php
include_once('header.php');
?>
<div class="page-wrapper">

    <div class="preloader"></div>

    <!--Project Single Section-->
    <section style="margin-bottom: 0px;" class="project-single-section projectsinglesection">

        <div class="auto-container">
            <h2 style="color: black; padding: 10px;">C-Type Power Press</h2>

            <div class="inner-container">
                <!--Upper Box-->

                <div class="upper-box">
                    <div class="single-item-carousel owl-carousel owl-theme">
                        <div class="slide">
                            <div style="display: flex;" class="image twentyfivemmimg">
                                <img style="height:300px; display:flex; width: 300px; border:1px solid #c9c9c9" src="images2/c-type.jpg" alt="" />
                                <div style=" text-align: justify;" class="text threeeighttext">
                            <h5 class="frame">FRAME:</h5>
                            <p>The frame is made of steel construction and their heavy cross section and rigiddesign assure minimum deflection and accurate alignment cast iron legs will be supplied up to 30 ton press.</p>
                            <h5>CRANK SHAFT:</h5>
                            <p>Crank shaft materials are made of special alloy steel to withstand the effective loadsitted in busher with high accuracy.</p>
                            <h5>GEARS & CLUTCH:</h5>
                            <p>The gears are made of cast steel or fabricated and it teeth are generated by hobbing the clutch is provided of pin/rolling key type also it is rigid and well supported for the mass production clutch can gives continuous stroke.</p>
                            <h5>FLYWHEEL:</h5>
                            <p>The flywheel is made of high grade cast iron and is balanced for strong and releasing adequate energy for the pressing operations.</p>
                             </div>
                        
                            </div>
                            <div >
                            <h5>LUBRICATION:</h5>
                            <p>An accurate lubrication system has been proved for lubrications the sliding surface and moving parts.</p>
                            <h5>TABLE & RAM:</h5>
                            <p>Table and ram are made of high grade heavy duty cast iron & properly seasoned. They are perfactly aligned to bach other to obtain high accuracy & precision press operation</p>
                            
                            </div>
                        </div>
                        <!-- <div class="slide">
                            <div class="image">
                                <img src="images/resource/image-5.jpg" alt="" />
                            </div>
                        </div>
                        <div class="slide">
                            <div class="image">
                                <img src="images/resource/image-5.jpg" alt="" />
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>
            <!-- <h2 class="title">London Wind Energy Plant</h2> -->
            <!-- <div class="load-more-option">
                    <ul class="clearfix">
                        <li class="prev pull-left"><a href="#"><span class="fa fa-angle-left"></span> Prev</a></li>
                        <li class="load-more"><a href="#"><span class="fa fa-th"></span></a></li>
                        <li class="next pull-right"><a href="#">Next <span class="fa fa-angle-right"></span></a></li>
                    </ul>
                </div> -->
            <div style="margin: -75px; margin-top:10px;" class="container mt-4">
                <table style="margin: auto;" class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>DESCRIPTION</th>
                            <th>3 TONS</th>
                            <th>5 TONS</th>
                            <th>10 TONS</th>
                            <th>10 TONS</th>
                            <th>20 TONS</th>
                            <th>20 TONS</th>
                            <th>30 TONS</th>
                            <th>30 TONS</th>
                            <th>50 TONS</th>
                            <th>50 TONS</th>
                            <th>75 TONS</th>
                            <th>100 TONS</th>
                            <th>150 TONS</th>
                            <th>200 TONS</th>
                            <th>250 TONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="alignLeft">Crank shaft diameter</td>
                            <td>38</td>
                            <td>51</td>
                            <td>60</td>
                            <td>60</td>
                            <td>76</td>
                            <td>76</td>
                            <td>83</td>
                            <td>83</td>
                            <td>105</td>
                            <td>105</td>
                            <td>121</td>
                            <td>134</td>
                            <td>152</td>
                            <td>158</td>
                            <td class="lastColumn">165</td>
                        </tr>
                        <tr class="even">
                            <td class="alignLeft">Stroke adjustment</td>
                            <td>2-25</td>
                            <td>6-25</td>
                            <td>6-25</td>
                            <td>6-51</td>
                            <td>13-51</td>
                            <td>13-76</td>
                            <td>13-63</td>
                            <td>13-76</td>
                            <td>13-76</td>
                            <td>13-102</td>
                            <td>115</td>
                            <td>127</td>
                            <td>152</td>
                            <td>158</td>
                            <td class="lastColumn">165</td>
                        </tr>
                        <tr>
                            <td class="alignLeft">Hole in ram</td>
                            <td>19</td>
                            <td>25</td>
                            <td>25.4</td>
                            <td>25.4</td>
                            <td>32</td>
                            <td>32</td>
                            <td>38</td>
                            <td>38</td>
                            <td>38</td>
                            <td>38</td>
                            <td>45</td>
                            <td>51</td>
                            <td>57</td>
                            <td>63</td>
                            <td class="lastColumn">63</td>
                        </tr>
                        <tr class="even">
                            <td class="alignLeft">Hole in bed</td>
                            <td>51</td>
                            <td>63</td>
                            <td>76</td>
                            <td>76</td>
                            <td>83</td>
                            <td>83</td>
                            <td>89</td>
                            <td>89</td>
                            <td>127</td>
                            <td>127</td>
                            <td>127</td>
                            <td>178</td>
                            <td>191</td>
                            <td>216</td>
                            <td class="lastColumn">229</td>
                        </tr>
                        <tr>
                            <td class="alignLeft">Length & width of bed</td>
                            <td>203*152</td>
                            <td>305*178</td>
                            <td>381*255</td>
                            <td>381*255</td>
                            <td>508*305</td>
                            <td>508*305</td>
                            <td>558*358</td>
                            <td>558*358</td>
                            <td>750*520</td>
                            <td>750*520</td>
                            <td>863*596</td>
                            <td>914*635</td>
                            <td>965*685</td>
                            <td>1016*736</td>
                            <td class="lastColumn">1067*778</td>
                        </tr>
                        <tr class="even">
                            <td class="alignLeft">Dist. bed to ram</td>
                            <td>127</td>
                            <td>153</td>
                            <td>205</td>
                            <td>205</td>
                            <td>280</td>
                            <td>280</td>
                            <td>292</td>
                            <td>292</td>
                            <td>406</td>
                            <td>406</td>
                            <td>483</td>
                            <td>483</td>
                            <td>495</td>
                            <td>519</td>
                            <td class="lastColumn">544</td>
                        </tr>
                        <tr>
                            <td class="alignLeft">Flywheel diameter</td>
                            <td>330</td>
                            <td>405</td>
                            <td>435</td>
                            <td>435</td>
                            <td>550</td>
                            <td>550</td>
                            <td>660</td>
                            <td>660</td>
                            <td>810</td>
                            <td>810</td>
                            <td>910</td>
                            <td>1016</td>
                            <td>1118</td>
                            <td>1150</td>
                            <td class="lastColumn">1320</td>
                        </tr>
                        <tr class="even">
                            <td class="alignLeft">Stroke per minute</td>
                            <td>85</td>
                            <td>85</td>
                            <td>75</td>
                            <td>75</td>
                            <td>60</td>
                            <td>60</td>
                            <td>60</td>
                            <td>60</td>
                            <td>55</td>
                            <td>55</td>
                            <td>50</td>
                            <td>45</td>
                            <td>40</td>
                            <td>30</td>
                            <td class="lastColumn">30</td>
                        </tr>
                        <tr>
                            <td class="alignLeft">H.P. Required</td>
                            <td>0.5</td>
                            <td>0.5</td>
                            <td>1</td>
                            <td>1</td>
                            <td>2</td>
                            <td>2</td>
                            <td>3</td>
                            <td>3</td>
                            <td>5</td>
                            <td>5</td>
                            <td>7.5</td>
                            <td>10</td>
                            <td>15</td>
                            <td>20</td>
                            <td class="lastColumn">25</td>
                        </tr>
                        <tr class="even">
                            <td class="alignLeft">Weight approx.</td>
                            <td>150</td>
                            <td>275</td>
                            <td>500</td>
                            <td>500</td>
                            <td>1000</td>
                            <td>1000</td>
                            <td>1350</td>
                            <td>1350</td>
                            <td>2750</td>
                            <td>2750</td>
                            <td>4200</td>
                            <td>5500</td>
                            <td>6600</td>
                            <td>9000</td>
                            <td class="lastColumn">11500</td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
        <div style="margin-top: 100px; margin-right:263px;" class="container">
            <p style="margin: 10px;">All dimensions are in MM.</p>
            <p style="margin: 10px;">As day to day improvements are contempated for better performance of the machine, we reserve the rights to alter the specifications without prior notice.</p>
            <p style="margin: 10px;">All the power presses combine durability with dependability. Years of experience in machinery has enabled us to offer the higest quality machine for accuracy with precision and heavy duty performance.</p>
            <p style="margin: 10px;">Acclaimed by actual users, the machines are gaining the evergrowing popularity in the field and no wonder therfore that machines are deing recommanded everywhere.
            </p>
        </div>
    </section>



    <?php
    include('footer.php')
    ?>
    <!-- End Main Footer -->



<!--End pagewrapper-->